package Dashboard;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import Dashboard.Products;
import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.JPanel;
/**

/**
 *
 * @author LENOVO
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        updateProductInfo(); 
    }
    
    public void setImageFromSrc(JPanel panel, String imageName) {
        panel.removeAll();
        try {
            // Ambil gambar dari dalam src/Dashboard/images/
            String path = "/gambar/" + imageName;
            ImageIcon icon = new ImageIcon(getClass().getResource(path));
            Image img = icon.getImage().getScaledInstance(panel.getWidth(), panel.getHeight(), Image.SCALE_SMOOTH);
            JLabel label = new JLabel(new ImageIcon(img));
            panel.setLayout(new BorderLayout());
            panel.add(label, BorderLayout.CENTER);
        } catch (Exception e) {
            System.out.println("Gagal load gambar: " + e.getMessage());
        }
        panel.revalidate();
        panel.repaint();
    }

    
    public void updateProductInfo() {
        MysqlProductsService service = new MysqlProductsService();
        
        // Laptop
        Products laptop = service.getProductByName("Laptop");
        if (laptop != null) {
            jLabelHargaLaptop.setText("Rp. " + laptop.getHarga());
            jLabelStokLaptop.setText(String.valueOf(laptop.getStok()));
            setImageFromSrc(jPanelLaptop, "laptop.png"); // nama file sesuai yg ada di /src/Dashboard/images/
        }
        
        // Mouse
        Products mouse = service.getProductByName("Mouse");
        if (mouse != null) {
            jLabelHargaMouse.setText("Rp. " + mouse.getHarga());
            jLabelStokMouse.setText(String.valueOf(mouse.getStok()));
            setImageFromSrc(jPanelMouse, "mouse.jpg");
        }
        
        
        // Keyboard
        Products keyboard = service.getProductByName("Keyboard");
        if (keyboard != null) {
            jLabelHargaKeyboard.setText("Rp. " + keyboard.getHarga());
            jLabelStokKeyboard.setText(String.valueOf(keyboard.getStok()));
            setImageFromSrc(jPanelKeyboard, "keyboard.jpg");
        }
        
        // Monitor
        Products monitor = service.getProductByName("Monitor");
        if (monitor != null) {
            jLabelHargaMonitor.setText("Rp. " + monitor.getHarga());
            jLabelStokMonitor.setText(String.valueOf(monitor.getStok()));
            setImageFromSrc(jPanelMonitor, "monitor.png");
        }
        
        
        // PowerBank
        Products PB = service.getProductByName("Powerbank");
        if (PB != null) {
            jLabelHargaPowerbank.setText("Rp. " + PB.getHarga());
            jLabelStokPowerbank.setText(String.valueOf(PB.getStok()));
            setImageFromSrc(jPanelPowerbank, "powerbank.jpg");
        }
        
        
        // Headset
        Products Headset = service.getProductByName("Headset");
        if (Headset != null) {
            jLabelHargaHeadset.setText("Rp. " + Headset.getHarga());
            jLabelStokHeadset.setText(String.valueOf(Headset.getStok()));
            setImageFromSrc(jPanelHeadset, "headset.png");
        }
        
        
        
        
    }

   
    


    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonSearchProducts = new javax.swing.JButton();
        jButtonCart = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelNamaProduk = new javax.swing.JLabel();
        jLabelHargaLaptop = new javax.swing.JLabel();
        jLabelHrg = new javax.swing.JLabel();
        jLabelStk = new javax.swing.JLabel();
        jLabelStokLaptop = new javax.swing.JLabel();
        jButtonTambahkanLaptop = new javax.swing.JButton();
        jPanelLaptop = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabelNamaProduk2 = new javax.swing.JLabel();
        jLabelHargaMouse = new javax.swing.JLabel();
        jLabelHrg2 = new javax.swing.JLabel();
        jLabelStk2 = new javax.swing.JLabel();
        jLabelStokMouse = new javax.swing.JLabel();
        jButtonTambahkanMouse = new javax.swing.JButton();
        jPanelMouse = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabelNamaProduk3 = new javax.swing.JLabel();
        jLabelHargaKeyboard = new javax.swing.JLabel();
        jLabelHrg3 = new javax.swing.JLabel();
        jLabelStk3 = new javax.swing.JLabel();
        jLabelStokKeyboard = new javax.swing.JLabel();
        jButtonTambahkanKeyboard = new javax.swing.JButton();
        jPanelKeyboard = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabelNamaProduk4 = new javax.swing.JLabel();
        jLabelHargaMonitor = new javax.swing.JLabel();
        jLabelHrg4 = new javax.swing.JLabel();
        jLabelStk4 = new javax.swing.JLabel();
        jLabelStokMonitor = new javax.swing.JLabel();
        jButtonTambahkanMonitor = new javax.swing.JButton();
        jPanelMonitor = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabelNamaProduk5 = new javax.swing.JLabel();
        jLabelHargaPowerbank = new javax.swing.JLabel();
        jLabelHrg5 = new javax.swing.JLabel();
        jLabelStk5 = new javax.swing.JLabel();
        jLabelStokPowerbank = new javax.swing.JLabel();
        jButtonTambahkanPowerbank = new javax.swing.JButton();
        jPanelPowerbank = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabelNamaProduk7 = new javax.swing.JLabel();
        jLabelHargaHeadset = new javax.swing.JLabel();
        jLabelHrg7 = new javax.swing.JLabel();
        jLabelStk7 = new javax.swing.JLabel();
        jLabelStokHeadset = new javax.swing.JLabel();
        jButtonTambahkanHeadset = new javax.swing.JButton();
        jPanelHeadset = new javax.swing.JPanel();

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 83, 154));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Saldo :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("100000");

        jButtonSearchProducts.setText("Cari produk");
        jButtonSearchProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchProductsActionPerformed(evt);
            }
        });

        jButtonCart.setText("Keranjang");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jButtonSearchProducts)
                .addGap(18, 18, 18)
                .addComponent(jButtonCart)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonSearchProducts)
                        .addComponent(jButtonCart)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabelNamaProduk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelNamaProduk.setText("Laptop");

        jLabelHargaLaptop.setText("...");

        jLabelHrg.setText("Harga");

        jLabelStk.setText("Stok:");

        jLabelStokLaptop.setText("...");

        jButtonTambahkanLaptop.setBackground(new java.awt.Color(130, 207, 255));
        jButtonTambahkanLaptop.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButtonTambahkanLaptop.setText("Tambah ke keranjang");

        jPanelLaptop.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanelLaptopLayout = new javax.swing.GroupLayout(jPanelLaptop);
        jPanelLaptop.setLayout(jPanelLaptopLayout);
        jPanelLaptopLayout.setHorizontalGroup(
            jPanelLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
        );
        jPanelLaptopLayout.setVerticalGroup(
            jPanelLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelHrg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelHargaLaptop))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelStk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelStokLaptop)))
                .addGap(58, 58, 58))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabelNamaProduk))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanelLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonTambahkanLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelNamaProduk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHargaLaptop)
                    .addComponent(jLabelHrg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelStokLaptop)
                    .addComponent(jLabelStk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTambahkanLaptop)
                .addGap(44, 44, 44))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabelNamaProduk2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelNamaProduk2.setText("Mouse");

        jLabelHargaMouse.setText("...");

        jLabelHrg2.setText("Harga");

        jLabelStk2.setText("Stok:");

        jLabelStokMouse.setText("...");

        jButtonTambahkanMouse.setBackground(new java.awt.Color(130, 207, 255));
        jButtonTambahkanMouse.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButtonTambahkanMouse.setText("Tambah ke keranjang");
        jButtonTambahkanMouse.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jButtonTambahkanMouseComponentResized(evt);
            }
        });

        jPanelMouse.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanelMouseLayout = new javax.swing.GroupLayout(jPanelMouse);
        jPanelMouse.setLayout(jPanelMouseLayout);
        jPanelMouseLayout.setHorizontalGroup(
            jPanelMouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
        );
        jPanelMouseLayout.setVerticalGroup(
            jPanelMouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabelHrg2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelHargaMouse))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabelStk2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelStokMouse)))
                .addGap(58, 58, 58))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabelNamaProduk2))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanelMouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonTambahkanMouse, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelMouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNamaProduk2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHargaMouse)
                    .addComponent(jLabelHrg2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelStokMouse)
                    .addComponent(jLabelStk2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTambahkanMouse)
                .addGap(44, 44, 44))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabelNamaProduk3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelNamaProduk3.setText("Keyboard");

        jLabelHargaKeyboard.setText("...");

        jLabelHrg3.setText("Harga");

        jLabelStk3.setText("Stok:");

        jLabelStokKeyboard.setText("...");

        jButtonTambahkanKeyboard.setBackground(new java.awt.Color(130, 207, 255));
        jButtonTambahkanKeyboard.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButtonTambahkanKeyboard.setText("Tambah ke keranjang");

        jPanelKeyboard.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanelKeyboardLayout = new javax.swing.GroupLayout(jPanelKeyboard);
        jPanelKeyboard.setLayout(jPanelKeyboardLayout);
        jPanelKeyboardLayout.setHorizontalGroup(
            jPanelKeyboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelKeyboardLayout.setVerticalGroup(
            jPanelKeyboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabelHrg3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelHargaKeyboard))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabelStk3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelStokKeyboard)))
                .addGap(58, 58, 58))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jButtonTambahkanKeyboard, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelKeyboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabelNamaProduk3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelKeyboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNamaProduk3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHargaKeyboard)
                    .addComponent(jLabelHrg3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelStokKeyboard)
                    .addComponent(jLabelStk3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTambahkanKeyboard)
                .addGap(44, 44, 44))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabelNamaProduk4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelNamaProduk4.setText("Monitor");

        jLabelHargaMonitor.setText("...");

        jLabelHrg4.setText("Harga");

        jLabelStk4.setText("Stok:");

        jLabelStokMonitor.setText("...");

        jButtonTambahkanMonitor.setBackground(new java.awt.Color(130, 207, 255));
        jButtonTambahkanMonitor.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButtonTambahkanMonitor.setText("Tambah ke keranjang");

        jPanelMonitor.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanelMonitorLayout = new javax.swing.GroupLayout(jPanelMonitor);
        jPanelMonitor.setLayout(jPanelMonitorLayout);
        jPanelMonitorLayout.setHorizontalGroup(
            jPanelMonitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelMonitorLayout.setVerticalGroup(
            jPanelMonitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabelHrg4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelHargaMonitor))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabelStk4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelStokMonitor)))
                .addGap(58, 58, 58))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jButtonTambahkanMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabelNamaProduk4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNamaProduk4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHargaMonitor)
                    .addComponent(jLabelHrg4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelStokMonitor)
                    .addComponent(jLabelStk4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTambahkanMonitor)
                .addGap(44, 44, 44))
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jLabelNamaProduk5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelNamaProduk5.setText("Power Bank");

        jLabelHargaPowerbank.setText("...");

        jLabelHrg5.setText("Harga");

        jLabelStk5.setText("Stok:");

        jLabelStokPowerbank.setText("...");

        jButtonTambahkanPowerbank.setBackground(new java.awt.Color(130, 207, 255));
        jButtonTambahkanPowerbank.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButtonTambahkanPowerbank.setText("Tambah ke keranjang");

        jPanelPowerbank.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanelPowerbankLayout = new javax.swing.GroupLayout(jPanelPowerbank);
        jPanelPowerbank.setLayout(jPanelPowerbankLayout);
        jPanelPowerbankLayout.setHorizontalGroup(
            jPanelPowerbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelPowerbankLayout.setVerticalGroup(
            jPanelPowerbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jButtonTambahkanPowerbank, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPowerbank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelNamaProduk5)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel12Layout.createSequentialGroup()
                            .addComponent(jLabelHrg5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabelHargaPowerbank))
                        .addGroup(jPanel12Layout.createSequentialGroup()
                            .addComponent(jLabelStk5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelStokPowerbank))))
                .addGap(58, 58, 58))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelPowerbank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNamaProduk5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHargaPowerbank)
                    .addComponent(jLabelHrg5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelStokPowerbank)
                    .addComponent(jLabelStk5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTambahkanPowerbank)
                .addGap(44, 44, 44))
        );

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));

        jLabelNamaProduk7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelNamaProduk7.setText("Headset");

        jLabelHargaHeadset.setText("...");

        jLabelHrg7.setText("Harga");

        jLabelStk7.setText("Stok:");

        jLabelStokHeadset.setText("..");

        jButtonTambahkanHeadset.setBackground(new java.awt.Color(130, 207, 255));
        jButtonTambahkanHeadset.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButtonTambahkanHeadset.setText("Tambah ke keranjang");

        jPanelHeadset.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanelHeadsetLayout = new javax.swing.GroupLayout(jPanelHeadset);
        jPanelHeadset.setLayout(jPanelHeadsetLayout);
        jPanelHeadsetLayout.setHorizontalGroup(
            jPanelHeadsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelHeadsetLayout.setVerticalGroup(
            jPanelHeadsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jLabelHrg7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelHargaHeadset))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jLabelStk7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelStokHeadset)))
                .addGap(58, 58, 58))
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(jButtonTambahkanHeadset, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelHeadset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabelNamaProduk7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelHeadset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNamaProduk7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHargaHeadset)
                    .addComponent(jLabelHrg7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelStokHeadset)
                    .addComponent(jLabelStk7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTambahkanHeadset)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 161, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSearchProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchProductsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSearchProductsActionPerformed

    private void jButtonTambahkanMouseComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButtonTambahkanMouseComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTambahkanMouseComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCart;
    private javax.swing.JButton jButtonSearchProducts;
    private javax.swing.JButton jButtonTambahkanHeadset;
    private javax.swing.JButton jButtonTambahkanKeyboard;
    private javax.swing.JButton jButtonTambahkanLaptop;
    private javax.swing.JButton jButtonTambahkanMonitor;
    private javax.swing.JButton jButtonTambahkanMouse;
    private javax.swing.JButton jButtonTambahkanPowerbank;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelHargaHeadset;
    private javax.swing.JLabel jLabelHargaKeyboard;
    private javax.swing.JLabel jLabelHargaLaptop;
    private javax.swing.JLabel jLabelHargaMonitor;
    private javax.swing.JLabel jLabelHargaMouse;
    private javax.swing.JLabel jLabelHargaPowerbank;
    private javax.swing.JLabel jLabelHrg;
    private javax.swing.JLabel jLabelHrg2;
    private javax.swing.JLabel jLabelHrg3;
    private javax.swing.JLabel jLabelHrg4;
    private javax.swing.JLabel jLabelHrg5;
    private javax.swing.JLabel jLabelHrg7;
    private javax.swing.JLabel jLabelNamaProduk;
    private javax.swing.JLabel jLabelNamaProduk2;
    private javax.swing.JLabel jLabelNamaProduk3;
    private javax.swing.JLabel jLabelNamaProduk4;
    private javax.swing.JLabel jLabelNamaProduk5;
    private javax.swing.JLabel jLabelNamaProduk7;
    private javax.swing.JLabel jLabelStk;
    private javax.swing.JLabel jLabelStk2;
    private javax.swing.JLabel jLabelStk3;
    private javax.swing.JLabel jLabelStk4;
    private javax.swing.JLabel jLabelStk5;
    private javax.swing.JLabel jLabelStk7;
    private javax.swing.JLabel jLabelStokHeadset;
    private javax.swing.JLabel jLabelStokKeyboard;
    private javax.swing.JLabel jLabelStokLaptop;
    private javax.swing.JLabel jLabelStokMonitor;
    private javax.swing.JLabel jLabelStokMouse;
    private javax.swing.JLabel jLabelStokPowerbank;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelHeadset;
    private javax.swing.JPanel jPanelKeyboard;
    private javax.swing.JPanel jPanelLaptop;
    private javax.swing.JPanel jPanelMonitor;
    private javax.swing.JPanel jPanelMouse;
    private javax.swing.JPanel jPanelPowerbank;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}